Improve type soundness of flags
This patch makes some changes to the API so that the bit flags are
are safer to use. There are a couple of related changes in this.

* Add a new module type "FLAG" that defines a `type flags = private int` and
  implements bitwise operations that preserve that the values remain
  valid as flags are combined.
* Include the new "FLAG" module in modules that define bit flags.
* Change the bindings functions to use the __Module__.flags instead of
  int. In cases where the flags have a default of 0, this argument is
  made optional so they don't have to be passed.
* Change the event types to use the flags types instead of int where
  appropriate (eg key modifiers)
* Update the numeric values of flags to match the C code. This doesn't
  necessarily improve soundness, but does make it easier to figure out
  what's going on in the debugger. This makes the flag conversions
  somewhat redundant, but I left them in.

The Flags module implementation defines the logical operators with these
signatures:

```ocaml
val lnot : flags -> int
val ( lor ) : flags -> flags -> flags
val ( land ) : flags -> int -> flags
val ( lxor ) : flags -> int -> int
```

I couldn't find a way to make the operators polymorphic, so `land` and
`lxor` require a type coercion `(:> int)` if you use a flag as the right
operand.

Here's an example of usage:

```ocaml

(* Good *)

let display_flags = Al5.Display.(windowed lor opengl lor frameless) in
Al5.set_new_display_flags display_flags

(* Caught at compile time *)

let display_flags = Al5.Display.windowed lor 0x0800
Error: The value Al5.Display.windowed has type Al5.Display.flags
       but an expression was expected of type int
```